replicaCount: 2

image:
  repository: ghcr.io/bakusivan/tradedex/tradedex
  pullPolicy: Always
  tag: "latest"
  imagePullSecrets: ghcr-secret

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

env:
  NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: ""
  NEXT_PUBLIC_ZEROEX_API_KEY: ""

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
